## Objective

<img src="https://imgur.com/Q67xlqY.png" width="500">

### Google Bigquery loves pandas & Jupyter. 

It is Really easy to use Google Big Query in Jupyter. The results of Google Big Query are easily transformed into `pd.DataFrame`, Python's core data analysis library.

### Dataset : Github Activity Log dataset

<img src="https://imgur.com/dBM4Xz1.png" width="500">

The entire github archive is also available as a public dataset on **Google BigQuery**: the dataset is automatically updated every hour and enables you to run arbitrary SQL-like queries over the entire dataset in seconds.

## [important] Credential setup

Please refer to the site([Getting Started with Authentication](https://cloud.google.com/docs/authentication/getting-started)) and receive the service account **json file** accessible to bigquery. 
Add it to the environment variable as below. With this setting, you can use Big Query easily without a separate authentication process.

In [17]:
import os

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = (
    os.path.abspath("../credentials/github-bigquery.json"))

### 1. Use `google`  Library

In [15]:
from google.cloud import bigquery
client = bigquery.Client()

In [16]:
google_df = client.query('''
SELECT *
FROM `githubarchive.day.20160101`
limit 1000;
''').to_dataframe()
google_df.head()

,type,public,payload,repo,actor,org,created_at,id,other
0,WatchEvent,True,"{""action"":""started""}","{'id': 10518659, 'name': 'tj/co', 'url': 'http...","{'id': 1693000, 'login': 'eatskolnikov', 'grav...",None,2016-01-01 19:51:57+00:00,3487330992,None
1,PushEvent,True,"{""push_id"":919982445,""size"":1,""distinct_size"":...","{'id': 44863781, 'name': 'Np3w/a', 'url': 'htt...","{'id': 10709829, 'login': 'Np3w', 'gravatar_id...",None,2016-01-01 15:39:09+00:00,3487158082,None
2,PushEvent,True,"{""push_id"":920111751,""size"":1,""distinct_size"":...","{'id': 325868, 'name': 'mv/vim', 'url': 'https...","{'id': 41629, 'login': 'mv', 'gravatar_id': ''...",None,2016-01-01 22:49:09+00:00,3487455584,None
3,WatchEvent,True,"{""action"":""started""}","{'id': 236571, 'name': 'rupa/z', 'url': 'https...","{'id': 7234098, 'login': 'yeafel', 'gravatar_i...",None,2016-01-01 05:42:56+00:00,3486870085,None
4,CreateEvent,True,"{""ref"":null,""ref_type"":""repository"",""master_br...","{'id': 48878154, 'name': 'Voyga/a', 'url': 'ht...","{'id': 9929523, 'login': 'Voyga', 'gravatar_id...",None,2016-01-01 12:59:40+00:00,3487063377,None

### 2. Use Pandas Method

In [3]:
import pandas as pd

pandas_df = pd.read_gbq('''
SELECT *
FROM `githubarchive.day.20160101`
limit 1000;
''')
pandas_df.head()

Downloading: 100%|██████████| 1000/1000 [00:02<00:00, 488.36rows/s]

,type,public,payload,repo,actor,org,created_at,id,other
0,WatchEvent,True,"{""action"":""started""}","{'id': 10518659, 'name': 'tj/co', 'url': 'http...","{'id': 1693000, 'login': 'eatskolnikov', 'grav...",None,2016-01-01 19:51:57+00:00,3487330992,None
1,PushEvent,True,"{""push_id"":919982445,""size"":1,""distinct_size"":...","{'id': 44863781, 'name': 'Np3w/a', 'url': 'htt...","{'id': 10709829, 'login': 'Np3w', 'gravatar_id...",None,2016-01-01 15:39:09+00:00,3487158082,None
2,PushEvent,True,"{""push_id"":920111751,""size"":1,""distinct_size"":...","{'id': 325868, 'name': 'mv/vim', 'url': 'https...","{'id': 41629, 'login': 'mv', 'gravatar_id': ''...",None,2016-01-01 22:49:09+00:00,3487455584,None
3,WatchEvent,True,"{""action"":""started""}","{'id': 236571, 'name': 'rupa/z', 'url': 'https...","{'id': 7234098, 'login': 'yeafel', 'gravatar_i...",None,2016-01-01 05:42:56+00:00,3486870085,None
4,CreateEvent,True,"{""ref"":null,""ref_type"":""repository"",""master_br...","{'id': 48878154, 'name': 'Voyga/a', 'url': 'ht...","{'id': 9929523, 'login': 'Voyga', 'gravatar_id...",None,2016-01-01 12:59:40+00:00,3487063377,None

### 3. Use Jupyter Magic Cell

#### Load Extension

In [4]:
%load_ext google.cloud.bigquery # load Extension

#### Query

````python
%%bigquery magic_cell_df # <- results will store in magic_cell_df

SELECT *
FROM `githubarchive.day.20160101`
limit 1000
````

In [7]:
%%bigquery magic_cell_df 

SELECT *
FROM `githubarchive.day.20160101`
limit 1000

In [8]:
magic_cell_df.head()

,type,public,payload,repo,actor,org,created_at,id,other
0,WatchEvent,True,"{""action"":""started""}","{'id': 10518659, 'name': 'tj/co', 'url': 'http...","{'id': 1693000, 'login': 'eatskolnikov', 'grav...",None,2016-01-01 19:51:57+00:00,3487330992,None
1,PushEvent,True,"{""push_id"":919982445,""size"":1,""distinct_size"":...","{'id': 44863781, 'name': 'Np3w/a', 'url': 'htt...","{'id': 10709829, 'login': 'Np3w', 'gravatar_id...",None,2016-01-01 15:39:09+00:00,3487158082,None
2,PushEvent,True,"{""push_id"":920111751,""size"":1,""distinct_size"":...","{'id': 325868, 'name': 'mv/vim', 'url': 'https...","{'id': 41629, 'login': 'mv', 'gravatar_id': ''...",None,2016-01-01 22:49:09+00:00,3487455584,None
3,WatchEvent,True,"{""action"":""started""}","{'id': 236571, 'name': 'rupa/z', 'url': 'https...","{'id': 7234098, 'login': 'yeafel', 'gravatar_i...",None,2016-01-01 05:42:56+00:00,3486870085,None
4,CreateEvent,True,"{""ref"":null,""ref_type"":""repository"",""master_br...","{'id': 48878154, 'name': 'Voyga/a', 'url': 'ht...","{'id': 9929523, 'login': 'Voyga', 'gravatar_id...",None,2016-01-01 12:59:40+00:00,3487063377,None